/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2019-04-02 13:51:17
*/
import { IMessage } from './IMessage';

export interface IPublisher {
  isConnected(): boolean;
  publish<T>(message: IMessage<T>): void;
}
