/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2019-04-02 13:51:17
*/
import { IMqttMessage } from './IMqttMessage';

export interface IPublisher {
  isConnected(): boolean;
  publish<T>(message: IMqttMessage<T>): void;
}
